# Generated by Django 5.1.7 on 2025-08-25 09:54

import diaspora.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('DIASPORA', 'Diaspora Office'), ('INVESTMENT', 'Investment Bureau'), ('LAND', 'City Land Management Bureau'), ('NIGID', 'Trade/License (Nigid)'), ('OTHER', 'Other')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diaspora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diaspora_id', models.CharField(default=diaspora.models.default_diaspora_id, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('primary_phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('country_of_residence', models.CharField(max_length=80)),
                ('city_of_residence', models.CharField(blank=True, max_length=120, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('expected_stay_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('is_returnee', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='English', max_length=30)),
                ('communication_opt_in', models.BooleanField(default=True)),
                ('address_local', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diasporas', to=settings.AUTH_USER_MODEL)),
                ('owner_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_diasporas', to='diaspora.office')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('INTAKE', 'Intake'), ('SCREENING', 'Screening'), ('REFERRAL', 'Referral'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='INTAKE', max_length=20)),
                ('overall_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DONE', 'Completed'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diaspora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='diaspora.diaspora')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVESTMENT', 'Investment'), ('TOURISM', 'Tourism'), ('FAMILY', 'Family'), ('STUDY', 'Study'), ('CHARITY_NGO', 'Charity/NGO'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=120, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=120, null=True)),
                ('investment_type', models.CharField(blank=True, max_length=80, null=True)),
                ('estimated_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('jobs_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('land_requirement', models.BooleanField(default=False)),
                ('land_size', models.FloatField(blank=True, null=True)),
                ('preferred_location_note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diaspora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='diaspora.diaspora')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='diaspora_pu_type_4b3d6d_idx'), models.Index(fields=['status'], name='diaspora_pu_status_fed5ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='SENT', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='diaspora.case')),
                ('from_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_referrals', to='diaspora.office')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_referrals', to='diaspora.office')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='diaspora_re_status_b60f45_idx'), models.Index(fields=['to_office', 'status'], name='diaspora_re_to_offi_31eba6_idx')],
            },
        ),
    ]
