# Generated by Django 5.1.7 on 2025-08-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaspora', '0002_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='recipients_groups',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='recipients_offices',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_for_internal',
            field=models.BooleanField(default=False),
        ),
    ]
